import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  section: {
    marginBottom: 20,
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  sectionTitle: {
    fontSize: 18,
    paddingBottom:8,
    fontWeight: 'bold',
    color: '#2C3E50',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  card: {
    backgroundColor: '#F9FBFD',
    borderRadius: 8,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#E0E6ED',
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#34495E',
    marginBottom: 4,
  },
  cardValue: {
    fontSize: 15,
    color: '#5D6D7E',
    marginBottom: 2,
  },
  cardSubtitle: {
    fontSize: 12,
    color: '#7F8C8D',
  },
  growthText: {
    color: '#28A745',
    fontWeight: 'bold',
  },
  filterContainer: {
    marginBottom: 10,
    position: 'relative',
  },
  dropdownButton: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#E0E6ED',
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 15,
    borderWidth: 1,
    borderColor: '#BDC3C7',
  },
  selectedText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#34495E',
  },
  dropdownList: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    borderRadius: 10,
    marginTop: 4,
    borderWidth: 1,
    borderColor: '#E0E6ED',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    zIndex: 1000,
  },
  dropdownItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  selectedItem: {
    backgroundColor: '#F8F9FA',
  },
  dropdownItemText: {
    fontSize: 16,
    color: '#5D6D7E',
    fontWeight: '400',
  },
  selectedItemText: {
    color: '#34495E',
    fontWeight: '600',
  },
  productCard: {
    flexDirection: 'row',
    alignItems: 'center',
   // backgroundColor: 'rgb(227, 227, 227)',
    borderRadius: 10,
    padding: 6,
    marginBottom: 10,
    borderBottomWidth: 1,
    borderColor: 'rgb(233, 234, 235)',
  },
  productImage: {
    width: 60,
    height: 60,
    borderRadius: 8,
    marginRight: 10,
    textAlign: 'center',
    lineHeight: 60,
  },
  productDetails: {
    flex: 1,
    justifyContent: 'center',
  },
  productName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#34495E',
  },
  productDescription: {
    fontSize: 12,
    color: '#7F8C8D',
    marginBottom: 3,
  },
  productStats: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  productInteraction: {
    fontSize: 12,
    color: '#7F8C8D',
    marginLeft: 5,
  },
  productPriceContainer: {
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    marginLeft: 10,
  },
  productPrice: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2C3E50',
    marginBottom: 5,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  statCard: {
    width: '48%',
    backgroundColor: '#F9FBFD',
    borderRadius: 8,
    padding: 16,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#E0E6ED',
    alignItems: 'center',
  },
  statValue: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#2C3E50',
  },
  statLabel: {
    fontSize: 14,
    color: '#7F8C8D',
    textAlign: 'center',
    marginBottom:6,
    letterSpacing: 1,
    textTransform: 'capitalize',
  },
  totalProductsRow: {
    backgroundColor: '#34495E',
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderRadius: 8,
    padding: 16,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: '#E0E6ED',
  },
  totalProductsLabel: {
    fontSize: 18,
    fontWeight: '600',
    marginTop:4,
    color: 'white',
    textAlign: 'center',
  },
  totalProductsValue: {
    fontSize: 28,
    fontWeight: 'bold',
    color: 'white',
    textAlign: 'center',
  },

});
