import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  headerButton: {
    marginHorizontal: 16,
    padding: 8,
  },
  container: {
    flex: 1,
    padding: 16,
    backgroundColor: '#FFFFFF',
  },
  productHeader: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 8,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  productImage: {
    width: 80,
    height: 80,
    borderRadius: 8,
  },
  productInfo: {
    flex: 1,
    justifyContent: 'center',
  },
  productName: {
    fontSize: Platform.OS === "ios" ?  16 : 14,
    fontWeight: 'bold',
    color: '#2C3E50',
    marginBottom: 4,
  },
  productCategory: {
    fontSize: 14,
    color: '#7F8C8D',
    marginBottom: 2,
  },
  productEan: {
    fontSize: 12,
    color: '#BDC3C7',
  },
  formContainer: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  sectionTitle: {
    fontSize: Platform.OS === "ios" ? 18 : 16,
    fontWeight: '600',
    color: '#2C3E50',
    marginBottom: 16,
  },
  inputGroup: {
    marginBottom: 16,
  },
  inputLabel: {
    fontSize: Platform.OS === "ios" ? 14 : 12,
    fontWeight: '500',
    color: '#34495E',
    marginBottom: 8,
  },
  textInput: {
    borderWidth: 1,
    borderColor: '#BDC3C7',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: Platform.OS === "ios" ? 14 : 12,
    color: '#2C3E50',
    backgroundColor: '#FAFBFC',
  },
  readOnlyContainer: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  readOnlyField: {
    flexDirection: 'row',
    marginBottom: 12,
  },
  readOnlyLabel: {
    fontSize: Platform.OS === "ios" ? 14 : 12,
    fontWeight: '500',
    color: '#34495E',
    width: 120,
  },
  readOnlyValue: {
    fontSize: Platform.OS === "ios" ? 14 : 12,
    color: '#7F8C8D',
    flex: 1,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
    marginBottom: 40,
  },
  cancelButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
   // backgroundColor: '#ECF0F1',
    borderRadius: 8,
    borderWidth:1,
    borderColor:'#E74C3C',
    paddingVertical: 12,
    marginRight: 8,
  },
  cancelButtonText: {
    fontSize: Platform.OS === "ios" ? 16 : 14,
    fontWeight: '600',
    color: '#E74C3C',
    marginLeft: 8,
  },
  saveButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#34495E',
    borderRadius: 8,
    paddingVertical: 12,
    marginLeft: 8,
  },
  saveButtonText: {
    fontSize: Platform.OS === "ios" ? 16: 14,
    fontWeight: '600',
    color: '#fff',
    marginLeft: 8,
  },
  imageContainer: {
    position: 'relative',
    marginRight: 16,
  },
  imageEditOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderRadius: 8,
  },
  imageEditBadge: {
    backgroundColor: '#007BFF',
    borderRadius: 20,
    padding: 8,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
});
