import { Platform, StyleSheet } from 'react-native';
export const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#fff',
    },
    header: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      justifyContent: 'space-between' as const,
      padding: 16,
      borderBottomWidth: 1,
      borderBottomColor: '#E0E6ED',
      backgroundColor: '#fff',
    },
    backButton: {
      padding: 8,
    },
    headerTitle: {
      fontSize: Platform.OS === "ios" ? 18 : 16,
      fontWeight: 'bold' as const,
      color: '#34495E',
    },
    resetButton: {
      padding: 8,
    },
    resetText: {
      color: '#34495E',
      fontSize: 14,
    },
    scrollContainer: {
      flex: 1,
      padding: 16,
    },
    section: {
      marginBottom: 24,
    },
    sectionTitle: {
      fontSize:  Platform.OS === "ios" ? 16 : 14,
      fontWeight: 'bold' as const,
      color: '#34495E',
      marginBottom: 12,
    },
    logoContainer: {
      alignSelf: 'center' as const,
      position: 'relative' as const,
    },
    logo: {
      width: 100,
      height: 100,
      borderRadius: 50,
      borderWidth: 2,
      borderColor: '#E0E6ED',
    },
    logoOverlay: {
      position: 'absolute' as const,
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(0,0,0,0.5)',
      borderRadius: 50,
      justifyContent: 'center' as const,
      alignItems: 'center' as const,
    },
    logoText: {
      color: '#fff',
      fontSize: 12,
      marginTop: 4,
    },
    coverImageContainer: {
      alignSelf: 'center' as const,
      position: 'relative' as const,
      width: '100%' as const,
      height: 150,
      borderRadius: 8,
      overflow: 'hidden' as const,
      borderWidth: 2,
      borderColor: '#E0E6ED',
    },
    coverImage: {
      width: '100%' as const,
      height: 150,
      resizeMode: 'cover' as const,
    },
    coverImageOverlay: {
      position: 'absolute' as const,
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'center' as const,
      alignItems: 'center' as const,
    },
    coverImageText: {
      color: '#fff',
      fontSize: Platform.OS === "ios" ? 14 :12,
      marginTop: 4,
    },
    inputContainer: {
      marginBottom: 16,
    },
    inputLabel: {
      fontSize:   Platform.OS === "ios" ? 14 : 12,
      fontWeight: '600' as const,
      color: '#34495E',
      marginBottom: 4,
    },
    input: {
      borderWidth: 1,
      borderColor: '#E0E6ED',
      borderRadius: 8,
      padding: 12,
      fontSize:  Platform.OS === "ios" ? 16 : 14,
      backgroundColor: '#F9FBFD',
    },
    inputError: {
      borderColor: '#e74c3c',
    },
    textArea: {
      borderWidth: 1,
      borderColor: '#E0E6ED',
      borderRadius: 8,
      padding: 12,
      fontSize:   Platform.OS === "ios" ? 16 :14,
      backgroundColor: '#F9FBFD',
      height: 80,
      textAlignVertical: 'top' as const,
    },
    charCount: {
      fontSize: 12,
      color: '#7F8C8D',
      textAlign: 'right' as const,
      marginTop: 4,
    },
    errorText: {
      fontSize: 12,
      color: '#e74c3c',
      marginTop: 4,
    },
    row: {
      flexDirection: 'row' as const,
      gap: 12,
    },
    flex1: {
      flex: 1,
    },
    hourRow: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      paddingVertical: 8,
      paddingHorizontal: 12,
      backgroundColor: '#F9FBFD',
      borderRadius: 8,
      marginBottom: 8,
    },
    dayText: {
      flex: 1,
      fontSize: Platform.OS === "ios" ? 16 : 12,
      fontWeight: '600' as const,
      color: '#34495E',
    },
    checkbox: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      marginRight: 12,
    },
    checkboxText: {
      fontSize:Platform.OS === "ios" ? 14 :12,
      color: '#34495E',
      marginLeft: 4,
    },
    timeInput: {
      borderWidth: 1,
      borderColor: '#E0E6ED',
      borderRadius: 6,
      padding: 8,
      fontSize:   Platform.OS === "ios" ? 14 :12,
      width: 70,
      textAlign: 'center' as const,
      backgroundColor: '#fff',
    },
    toText: {
      fontSize: Platform.OS === "ios" ? 14 :12,
      color: '#7F8C8D',
      marginHorizontal: 8,
    },
    addHolidayContainer: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      marginBottom: 16,
      gap: 8,
    },
    dateButton: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      padding: 12,
      backgroundColor: '#F9FBFD',
      borderRadius: 8,
      borderWidth: 1,
      borderColor: '#E0E6ED',
      flex: 1,
    },
    dateButtonText: {
      fontSize:Platform.OS === "ios" ? 14 :12,
      color: '#34495E',
      marginLeft: 8,
    },
    reasonInput: {
      flex: 2,
      borderWidth: 1,
      borderColor: '#E0E6ED',
      borderRadius: 8,
      padding: 12,
      fontSize:   Platform.OS === "ios" ? 14 :12,
      backgroundColor: '#F9FBFD',
    },
    addButton: {
      backgroundColor: '#34495E',
      padding: 12,
      borderRadius: 8,
      justifyContent: 'center' as const,
      alignItems: 'center' as const,
    },
    holidaysList: {
      gap: 8,
    },
    holidayItem: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      padding: 12,
      backgroundColor: '#F9FBFD',
      borderRadius: 8,
      borderWidth: 1,
      borderColor: '#E0E6ED',
    },
    holidayInfo: {
      flex: 1,
    },
    holidayDate: {
      fontSize:  Platform.OS === "ios" ? 14 :12,
      fontWeight: '600' as const,
      color: '#34495E',
    },
    holidayReason: {
      fontSize: 12,
      color: '#7F8C8D',
      marginTop: 2,
    },
    removeButton: {
      padding: 4,
    },
    footer: {
      flexDirection: 'row' as const,
      padding: 16,
      margin:16,
      borderTopWidth: 1,
      borderTopColor: '#E0E6ED',
      backgroundColor: '#fff',
      gap: 12,
    },
    button: {
      flex: 1,
      padding: 14,
      borderRadius: 8,
      alignItems: 'center' as const,
    },
    cancelButton: {
      backgroundColor: '#F9FBFD',
      borderWidth: 1,
      borderColor: '#e31414',
    },
    cancelButtonText: {
      color: '#e31414',
      fontSize: Platform.OS === "ios" ? 16 : 14,
      fontWeight: '600' as const,
    },
    saveButton: {
      backgroundColor: '#34495E',
    },
    saveButtonText: {
      color: '#fff',
      fontSize: Platform.OS === "ios" ? 16 : 14,
      fontWeight: '600' as const,
    },
    disabledButton: {
      backgroundColor: '#BDC3C7',
    },
    disabledText: {
      color: '#7F8C8D',
    },
    headerCenter: {
      flex: 1,
      alignItems: 'center' as const,
    },
    stepIndicator: {
      flexDirection: 'row' as const,
      justifyContent:'center',
      marginTop: 12,
      marginBottom:8,
    },
    stepContainer: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
    },
    stepCircle: {
      width: 30,
      height: 30,
      borderRadius: 15,
      borderWidth: 2,
      borderColor: '#E0E6ED',
      backgroundColor: '#fff',
      justifyContent: 'center' as const,
      alignItems: 'center' as const,
    },
    stepCircleActive: {
      borderColor: '#34495E',
      backgroundColor: '#34495E',
    },
    stepNumber: {
      fontSize: 12,
      fontWeight: '600' as const,
      color: '#7F8C8D',
    },
    stepNumberActive: {
      color: '#fff',
    },
    stepLine: {
      width: 20,
      height: 2,
      backgroundColor: '#E0E6ED',
      marginHorizontal: 4,
    },
    previousButton: {
      backgroundColor: '#F9FBFD',
      borderWidth: 1,
      borderColor: '#34495E',
      flexDirection: 'row' as const,
      gap: 8,
    },
    previousButtonText: {
      color: '#34495E',
      fontSize: Platform.OS === "ios" ? 16 : 14,
      fontWeight: '600' as const,
    },
    nextButton: {
      backgroundColor: '#34495E',
      flexDirection: 'row' as const,
      gap: 8,
    },
    nextButtonText: {
      color: '#fff',
      fontSize: Platform.OS === "ios" ? 16 : 14,
      fontWeight: '600' as const,
    },
  });