import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  modalContainer: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.5)', justifyContent: 'center', alignItems: 'center', padding: 20 },
  modalContent: { backgroundColor: '#FFFFFF', borderRadius: 20, maxHeight: '90%', width: '100%', maxWidth: 500, paddingBottom: 20, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 8, elevation: 10 },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingVertical:12, borderBottomWidth: 1, borderBottomColor: '#ECF0F1' },
  headerTitle: { fontSize: Platform.OS === "ios" ? 20 : 16, fontWeight: 'bold', color: '#2C3E50' },
  closeButton: { padding: 8 },
  scrollContent: { paddingHorizontal: 20 },
  stepIndicator: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', paddingVertical: 20 },
  stepContainer: { flexDirection: 'row', alignItems: 'center' },
  stepCircle: { width: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center', marginHorizontal: 8 },
  stepCompleted: { backgroundColor: '#27AE60' },
  stepActive: { backgroundColor: '#3498DB' },
  stepPending: { backgroundColor: '#BDC3C7' },
  stepLine: { width: 40, height: 2, backgroundColor: '#BDC3C7', marginHorizontal: 4 },
  stepLineCompleted: { backgroundColor: '#27AE60' },
  stepNumber: { fontSize: 14, fontWeight: '600' },
  stepNumberActive: { color: '#FFFFFF' },
  stepNumberPending: { color: '#FFFFFF' },
  section: { marginBottom: Platform.OS === "ios" ? 16 : 14 },
  sectionTitle: { fontSize:Platform.OS === "ios" ? 16 : 14, fontWeight: '600', color: '#34495E', marginBottom: 12 },
  inputGroup: { marginBottom: 16 },
  inputLabel: { fontSize: Platform.OS === "ios" ? 14 : 12, fontWeight: '500', color: '#34495E', marginBottom: 6 },
  inputLabelRequired: { color: '#34495E' },
  textInput: { borderWidth: 1, borderColor: '#BDC3C7', borderRadius: 8, paddingHorizontal: 12, paddingVertical: 10, fontSize:Platform.OS === "ios" ? 16 : 14, color: '#2C3E50', backgroundColor: '#FFFFFF' },
  eanInput: { fontSize: Platform.OS === "ios" ? 16 : 14, fontWeight: '600', textAlign: 'center', letterSpacing: 2 },
  manufacturerCodeInput: { borderColor: '#F39C12', borderWidth: 1.5, backgroundColor: '#FFF9E6' },
  manufacturerCodeLabel: { fontWeight: '600', color: '#34495E' },
  manufacturerCodeHint: { fontSize: 12, color: '#7F8C8D', marginTop: 4, fontStyle: 'italic' },
  searchButton: { backgroundColor: '#34495E', paddingVertical: 11, paddingHorizontal: 16, borderRadius: 6, marginLeft: 8 },
  searchButtonPending: { backgroundColor: '#BDC3C7' },
  searchButtonText: { color: '#FFFFFF', fontSize: 14, fontWeight: '600' },
  matchCard: { backgroundColor: '#FFFFFF', borderRadius: 12, padding: 16, marginBottom: 12, borderWidth: 1, borderColor: '#ECF0F1', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4, elevation: 3 },
  matchCardSelected: { borderColor: '#3498DB', borderWidth: 2 },
  matchImage: { width: 60, height: 60, borderRadius: 8, marginRight: 12 },
  matchInfo: { flex: 1 },
  matchName: { fontSize: 16, fontWeight: '600', color: '#2C3E50', marginBottom: 4 },
  matchBrand: { fontSize: 14, color: '#7F8C8D', marginBottom: 2 },
  matchManufacturer: { fontSize: 12, color: '#95A5A6' },
  productSheet: { backgroundColor: '#F8F9FA', borderRadius: 12, padding: 16, marginBottom: 20 },
  productSheetTitle: { fontSize: 18, fontWeight: 'bold', color: '#2C3E50', marginBottom: 12 },
  productImages: { flexDirection: 'row', marginBottom: 12 },
  productImage: { width: 80, height: 80, borderRadius: 8, marginRight: 8 },
  productDescription: { fontSize: 14, color: '#34495E', lineHeight: 20, marginBottom: 12 },
  specRow: { flexDirection: 'row', marginBottom: 6 },
  specLabel: { fontSize: 12, fontWeight: '600', color: '#34495E', width: 100 },
  specValue: { fontSize: 12, color: '#7F8C8D', flex: 1 },
  loadingContainer: { alignItems: 'center', paddingVertical: 40 },
  loadingText: { marginTop: 12, fontSize: 14, color: '#7F8C8D' },
  errorContainer: { backgroundColor: '#FDEDEC', borderRadius: 8, padding: 16, marginBottom: 16, borderLeftWidth: 4, borderLeftColor: '#E74C3C' },
  errorText: { color: '#E74C3C', fontSize: 14 },
  actionButtons: { flexDirection: 'row', paddingHorizontal: 20, paddingVertical: 12, borderTopWidth: 1, borderTopColor: '#ECF0F1', backgroundColor: '#FFFFFF' },
  actionButton: { flex: 1, paddingVertical:Platform.OS === "ios" ? 12 : 10, borderRadius: 8, alignItems: 'center', marginHorizontal: 4 },
  primaryButton: { backgroundColor: '#34495E' },
  secondaryButton: { backgroundColor: '#BDC3C7' },
  actionButtonText: { fontSize: Platform.OS === "ios" ? 16 : 14, fontWeight: '600', color: '#FFFFFF' },
  secondaryButtonText: { color: '#34495E' },
  imageUploadButton: { borderWidth: 1, borderColor: '#BDC3C7', borderRadius: 8, borderStyle: 'dashed', padding: 0, alignItems: 'center', justifyContent: 'center', minHeight: 120, overflow: 'hidden' },
  imageUploadPlaceholder: { alignItems: 'center', padding: 20 },
  imageUploadText: { marginTop: 8, fontSize: 14, color: '#BDC3C7', textAlign: 'center' },
  imagePreviewContainer: { position: 'relative', width: '100%', height: 120 },
  imagePreview: { width: '100%', height: 120, borderRadius: 8 },
  imageOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0, 0, 0, 0.5)', borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  imageOverlayText: { color: '#FFFFFF', fontSize: 12, fontWeight: '600', marginTop: 4 },
});
