import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F4F7FC',
  },
  container: {
    //paddingVertical: 20,
    paddingHorizontal: 12,
  },
  header: {
      flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#34495E',
    paddingTop: 60,
    padding:18,
   // borderBottomLeftRadius: 20,
   // borderBottomRightRadius: 20,
   // marginBottom: 20,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  backButton: {
    marginRight: 15,
  },
  editButton: {
    margin:15,
  },
  editmain:{
    alignItems:'flex-end',
  },
  headerRight: {
    width: 24, // To balance the layout
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
  },
  mainCon:{
    backgroundColor:'#fff',
    marginBottom:12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderRadius:12
  },
  coverImageContainer: {
    marginBottom: 80, 
    borderRadius: 10,
    overflow: 'visible',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    position: 'relative', // Added relative positioning for absolute logo positioning
  },
  coverImage: {
    width: '100%',
    height: 100,
    resizeMode: 'cover',
    borderTopLeftRadius:16,
    borderTopRightRadius:16
  },
  coverImageOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  coverImageText: {
    color: '#fff',
    fontSize:   Platform.OS === "ios" ? 14 : 12,
    fontWeight: '600',
    marginTop: 8,
  },
  storeInfoOverlay: {
    position: 'absolute',
    top: 109,
    marginLeft:118,
   // left: 95,
    //right: 15,
    alignItems: 'baseline',
  },
  logo: {
    width: 90,
    height: 90,
   // borderRadius: 50,
   // borderWidth: 2,
   // borderColor: '#E0E6ED',
    position: 'absolute',
    bottom: -50, // Half overlap: logo extends 50px below cover image
    left: '17%',
    marginLeft: -50, 
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  storeName: {
    fontSize:  Platform.OS === "ios" ? 22 : 18,
    fontWeight: 'bold',
    color: '#2C3E50',
    marginBottom: 5,
  },
  storeAddress: {
    fontSize: 14,
    color: '#7F8C8D',
    textAlign: 'center',
  },
  storeNameOverlay: {
    fontSize:Platform.OS === "ios" ? 22 : 18,
    fontWeight: 'bold',
    color: '#33467',
    marginBottom: 5,
   // textShadowColor: 'rgba(0, 0, 0, 0.7)',
   // textShadowOffset: { width: 0, height: 1 },
   // textShadowRadius: 3,
  },
  storeAddressOverlay: {
    fontSize: Platform.OS === "ios" ? 14 : 12,
    color: '#33460',
    textAlign: 'left',
   // textShadowColor: 'rgba(0, 0, 0, 0.7)',
   // textShadowOffset: { width: 0, height: 1 },
   // textShadowRadius: 3,
  },
  section: {
    marginBottom: 20,
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  sectionTitle: {
    fontSize: Platform.OS === "ios" ? 18 : 14,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#2C3E50',
  },
  sectionContent: {
    fontSize:Platform.OS === "ios" ? 15 : 12,
    color: '#5D6D7E',
    lineHeight: 22,
  },
  categoryContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#F8F9FA',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E9ECEF',
  },
  categoryText: {
    fontSize: Platform.OS === "ios" ? 14 : 12,
    color: '#34495E',
    fontWeight: '600',
    marginLeft: 8,
  },
  servicesContainer: {
   // paddingLeft: 10,
  },
  serviceItem: {
    fontSize: 15,
    color: '#5D6D7E',
    marginBottom: 5,
  },
  locationContainer: {
   // paddingLeft: 10,
  },
  locationItem: {
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  locationItemText: {
    fontSize: Platform.OS === "ios" ? 15 : 12,
    color: '#5D6D7E',
    marginLeft: 8,
  },
  hoursContainer: {
   // paddingLeft: 10,
  },
  hourItem: {
    fontSize: Platform.OS === "ios" ? 15 : 12,
    color: '#5D6D7E',
    marginBottom: 4,
  },
  vacationText: {
    fontSize:Platform.OS === "ios" ? 15 : 12,
    color: '#E74C3C',
    marginTop: 8,
    fontWeight: '500',
  },
  galleryScroll: {
    marginBottom: 10,
  },
  galleryImage: {
    width: 150,
    height: 100,
    borderRadius: 8,
    marginRight: 10,
    resizeMode: 'cover',
    borderWidth: 1,
    borderColor: '#E0E6ED',
  },
  uploadButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ECF0F1',
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#BDC3C7',
    marginTop: 10,
  },
  uploadButtonText: {
    fontSize:Platform.OS === "ios" ?  16 : 12,
    color: '#34495E',
    marginLeft: 5,
    fontWeight: '600',
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  loadingText: {
    fontSize: Platform.OS === "ios" ? 16 : 14,
    color: '#34495E',
    textAlign: 'center',
  },
  errorText: {
    fontSize:Platform.OS === "ios" ?  16 : 14,
    color: '#e74c3c',
    textAlign: 'center',
    marginTop: 10,
    marginBottom: 20,
  },
  retryButton: {
    backgroundColor: '#34495E',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
  },
  retryButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  holidaysContainer: {
    paddingLeft: 10,
  },
  holidayItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    padding: 8,
    backgroundColor: '#F9FBFD',
    borderRadius: 6,
  },
  holidayInfo: {
    marginLeft: 10,
    flex: 1,
  },
  holidayDate: {
    fontSize: 14,
    fontWeight: '600',
    color: '#34495E',
  },
  holidayReason: {
    fontSize: 12,
    color: '#7F8C8D',
    marginTop: 2,
  },
});
